services:
  db:
    image: mysql:8.0.33
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root1223
      MYSQL_DATABASE: mango
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ../data/db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis_data:/data
  
  app:
    build:
      context: .
      dockerfile: API.Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/../data/db-data
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/../data/redis-data